version: '3.9'
services:
  mysql-commonify:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql-commonify:/data/db 
  phpmyadmin-commonify:
    image: phpmyadmin
    links: 
      - mysql-commonify
    restart: always
    ports:
      - 3005:80
    environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    - PMA_ARBITRARY=1
    - UPLOAD_LIMIT=1500M
volumes:
  reactVolume:
  nodeVolume:
  mysql-commonify: